### ISSUE TITLE
Are there limits on the number of requests?

### ISSUE THREAD

**Issue by dvijnru** [mcstatus-io/ping-server#12]
Hello, I want to say thank you for the service
Please tell me, I need constant up-to-date information, I have disabled caching
When I make several requests in a row the IP address, I get the message - online: false
If you pause for 5 seconds, it returns online: true
Are there limits on the number of requests?

**Comment by PassTheMayo** [comment]
There shouldn't be anything that is limiting the amount of requests that you can make, as long as you're hosting this software yourself. Can you provide any more information so I can reproduce this issue, such as a server host that you're trying to retrieve? It's possible that this is the server limiting the requests and not this software.

**Comment by dvijnru** [comment]
I'm sorry, I must have made a mistake.
I tested it on your demo server, the information is coming in
http://94.250.254.213:3001/status/java/demo.mcstatus.io
Is protection on the minecraft server probably worth it?
http://94.250.254.213:3001/status/java/mfs.pw
If you send multiple requests in a row to the server mfs.pw - Displays "online":false

**Comment by PassTheMayo** [comment]
Apologies for the late reply, this notification got pushed down on my GitHub and emails. There is no code within the ping server or `mcutil` library that is rate-limiting the requests to each server, so if you are seeing `online: false` then this is most likely the server itself rate-limiting you. I can confirm that my demo server (`demo.mcstatus.io`) does not have rate-limiting so I am unsure of why if you are seeing offline responses, could be an issue with my demo server itself. Most public Minecraft servers today do implement some sort of anti-DDoS system that limits the amount of status requests per interval, which would explain the case for the `mfs.pw` server.
