### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Project-Econome** [mcstatus-io/ping-server#16]
Hello I was wondering if I could have help setting up the ping server as I have done the older one but I do not quite understand the redis and mongoDB stuff

**Comment by PassTheMayo** [comment]
The MongoDB and Redis dependencies are optional and can be configured in the `config.yml` to not be used, by using the following configuration values:

```yaml
mongodb: ~
redis: ~
```

**Comment by Project-Econome** [comment]
thank you!

**Comment by Project-Econome** [comment]
hello i am tring to do this via github pages or vercel can you give me some steps to set it up if its not possible on either will it be possible on heroku?

**Comment by PassTheMayo** [comment]
You won't be able to host the ping server on GitHub Pages or Vercel because those are just static content hosts. Heroku would be your only free option.
