### ISSUE TITLE
Issue with MongoDB URL on Docker?

### ISSUE THREAD

**Issue by Exoduslocal** [mcstatus-io/ping-server#19]
I'm trying to run ping-server via Docker on port 3069 locally, which is the only change I've made. However, I'm encountering a MongoDB-related error. I noticed there's an environment variable for MongoDB in the configuration, but it doesn't seem to be getting created within the Docker container. 

Below are the logs of what happens when ping-server starts. 

024-09-17 23:53:33 2024/09/17 22:53:33 Successfully retrieved EULA blocked servers
2024-09-17 23:53:33 2024/09/17 22:53:33 Failed to connect to MongoDB: error parsing uri: scheme must be "mongodb" or "mongodb+srv"

**Comment by PassTheMayo** [comment]
The MongoDB instance should be hosted separately from the `ping-server` container. By default, the configuration is set to not attempt to connect to any MongoDB instance. If you want to manually configure this, you can set the following value in the `config.yml` file:

```yaml
mongodb: ~
```

If you are wanting to specify a MongoDB instance, it should be in the form of a full URI, like this:

```yaml
mongodb: mongodb://username:password@hostname:port/databasename
```

**Comment by Exoduslocal** [comment]
Hey Mayo

Thank you for the prompt response. The solution you provided using ~ worked perfectly. I also tested the ping-server container on both my Windows 11 PC and Ubuntu 24.04 without making any changes and encountered the same error. 

Just another question If was going to use MongoDB, I'm guessing the tables needed are automatic created or would I needed to do that on my end?

**Comment by PassTheMayo** [comment]
Interesting, I will have to look into this issue with the default configuration. Also yes, the MongoDB tables will automatically be created, but you may have to create the database yourself. For almost 99.9% of deployments by users of this repository, you will never have to use MongoDB. That is currently only used for requiring authentication with accounts created on the dashboard, which you would then have to host the dashboard too (which is still under construction). I would recommend keeping MongoDB disabled, but Redis is definitely recommended for caching server statuses.

**Comment by Exoduslocal** [comment]
Thanks for the information. One last question: Is there a way to limit who the API responds to? I plan to use this API on a VPS hosted on AWS. Is there a way to ensure the API only responds to requests from my application and not others? I assume this is where the account system comes into play?

**Comment by PassTheMayo** [comment]
If you want to limit requests to only allow one application, I would recommend hosting an Nginx/Apache web server and serve the ping server behind a reverse proxy. Using Nginx/Apache in front of the ping server will allow you to filter requests by IP address, an authentication header, or whatever other method you choose. This would be more practical than setting up a MongoDB database just to use a single account.

I may implement something into the ping server itself to allow denial of requests from certain IP addresses or requests that don't have a specific `Authorization` header set.
