### ISSUE TITLE
Feature: refactor status.go

### ISSUE THREAD

**Issue by dailypush** [mcstatus-io/ping-server#3]
Looking at ways and thoughts  to refactor status.go 
There is duplicate code in the respective methods for bedrock and java.

Maybe create an interface called getStatus that can be invoked for either.

The getStatus function could utilize the Redis caching mechanism for storing and retrieving server statuses. Additionally, how about a IsBlockedAddress function to check if a server address is blocked by EULA, which could be integrated into the FetchJavaStatus and FetchBedrockStatus functions. These updates enable more efficient server status retrieval by reducing redundant calls to fetch fresh data and help maintain compliance with EULA restrictions.

Even further thought would be break this package up in go to respective bedrock.go and java.go… that might make it more modular and simplistic to make enhancements.

**Comment by PassTheMayo** [comment]
Refactoring the status.go file could definitely be beneficial to reducing the complexity of getting the statuses. The only issue about making the `GetStatus()` a single function that can return either Java or Bedrock Edition statuses is that the return type has to be generic, meaning that other routes like `/icon/:address` will have to coerce the generic type back into a `JavaStatusResponse` type. If you can think of a way around this or have an idea about how to refactor, go ahead and open a pull request and we can work together on it.
