### ISSUE TITLE
Bug Report: API Always Returns Default Port (25565) with SRV Record Server

### ISSUE THREAD

**Issue by WooMai** [mcstatus-io/ping-server#9]
The API appears to be returning the correct information, but the wrong port.

![](https://img.trumpdns.com/2023/08/22/8DP04CuA.png)

This issue was also reproduced using api.mcsrvstat.us.

I'm not familiar with Golang, so unfortunately, I am unable to submit a PR for this.

I did some brief research:
It seems like the `ParseAddress()` function does not check the SRV records. Instead, it simply splits the string and returns the default port if no port is specified in the input. 
However, in [mcutil](https://github.com/mcstatus-io/mcutil/blob/main/status.go#L95), the SRV record is properly checked, but `GetJavaStatus()` still returns the incorrect port 25565.

**Comment by PassTheMayo** [comment]
The `host` and `port` properties in the response were not designed to change if the server had an SRV record, it's used to confirm the address sent via the request URL. The SRV lookup is done internally, which I'm considering adding to the response data in a `debug` property along with other DNS information.

I'll keep this issue open as an implementation tracker, and I'll begin working tonight on that.

**Comment by PassTheMayo** [comment]
I've implemented a different solution to showing SRV record information. If the server is online, the response will have an `srv_record` property which is either `null` or an object, depending if the lookup was successful or not. These charges are now live and you should be able to see this on the responses.
